public class DriverJava{

static String[] tests = {
"checkTile 1 one",
"False",
"checkTile 2 one",
"False",
"checkTile 3 one",
"True",
"checkTile 4 one",
"False",
"checkTile 5 one",
"False",
"checkTile 6 one",
"True",
"checkTile 7 one",
"False",
"checkTile 8 one",
"False",
"checkTile 9 one",
"True",
"checkTile 12 one",
"True",
"checkTile 0 one",
"False",
"checkTile 13 one",
"False",
"checkTile 1 two",
"True",
"checkTile 2 two",
"True",
"checkTile 3 two",
"True",
"checkTile 4 two",
"False",
"checkTile 5 two",
"True",
"checkTile 6 two",
"False",
"checkTile 7 two",
"True",
"checkTile 8 two",
"False",
"checkTile 9 two",
"False",
"checkTile 10 two",
"True",
"checkTile 11 two",
"True",
"checkTile 12 two",
"True",
"checkTile 0 two",
"False",
"checkTile 13 two",
"False",
"checkTile 1 three",
"True",
"checkTile 2 three",
"True",
"checkTile 3 three",
"True",
"checkTile 4 three",
"False",
"checkTile 5 three",
"True",
"checkTile 6 three",
"True",
"checkTile 7 three",
"False",
"checkTile 8 three",
"False",
"checkTile 9 three",
"True",
"checkTile 10 three",
"True",
"checkTile 11 three",
"True",
"checkTile 12 three",
"True",
"checkTile 0 three",
"False",
"checkTile 13 three",
"False",
"checkTile 1 four",
"True",
"checkTile 2 four",
"False",
"checkTile 3 four",
"True",
"checkTile 4 four",
"True",
"checkTile 5 four",
"True",
"checkTile 6 four",
"True",
"checkTile 7 four",
"False",
"checkTile 8 four",
"False",
"checkTile 9 four",
"True",
"checkTile 10 four",
"False",
"checkTile 11 four",
"False",
"checkTile 12 four",
"True",
"checkTile 0 four",
"False",
"checkTile 13 four",
"False",
"checkTile 1 five",
"True",
"checkTile 2 five",
"True",
"checkTile 3 five",
"True",
"checkTile 4 five",
"True",
"checkTile 5 five",
"True",
"checkTile 6 five",
"True",
"checkTile 7 five",
"False",
"checkTile 8 five",
"False",
"checkTile 9 five",
"True",
"checkTile 10 five",
"True",
"checkTile 11 five",
"True",
"checkTile 12 five",
"True",
"checkTile 0 five",
"False",
"checkTile 13 five",
"False",
"isEmptyOnThree 1 3",
"False",
"isEmptyOnThree 2 3",
"False",
"isEmptyOnThree 3 3",
"False",
"isEmptyOnThree 4 3",
"True",
"isEmptyOnThree 5 3",
"False",
"isEmptyOnThree 6 3",
"False",
"isEmptyOnThree 7 3",
"True",
"isEmptyOnThree 8 3",
"True",
"isEmptyOnThree 9 3",
"False",
"isEmptyOnThree 10 3",
"False",
"isEmptyOnThree 11 3",
"False",
"isEmptyOnThree 12 3",
"False",
"isEmptyOnThree 0 3",
"invalid",
"isEmptyOnThree 13 3",
"invalid",
"isEmptyOnThree 21 4",
"invalid",
"isEmptyOnThree 1 2",
"invalid",
};
public static String getTest(int i){
return tests[i];
}
	
public static String getResult(int i){
return tests[i+1];
}
}